import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Danny',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
      collectionID: 1,
      deckIDs: [],
      cardCollection: [
        {
          name: 'Ash Blossom & Joyous Spring',
          slug: 'ash-blossom-and-joyous-spring',
          count: 2,
        },
        {
          name: 'Tearlaments Scheiren',
          slug: 'tearlaments-scheiren',
          count: 1,
        },
      ],
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
      collectionID: 2,
      deckIDs: [],
    },
  ],
  products: [
    {
      name: 'Ash Blossom & Joyous Spring',
      type: 'tuner monster',
      race: 'zombie',
      attribute: 'fire',
      level: 3,
      atk: 0,
      def: 1800,
      desc: `During either player's turn, when a card or effect is activated that includes any of these effects: You can discard this card; negate that effect.
- Add a card from the Deck to the hand.
- Special Summon from the Deck.
- Send a card from the Deck to the Graveyard.
You can only use this effect of "Ash Blossom & Joyous Spring" once per turn.`,
      card_sets: [
        {
          set_name: "2022 Tin of the Pharaoh's Gods",
          set_code: 'MP22-EN257',
          set_rarity: 'Prismatic Secret Rare',
          set_rarity_code: '(P5cR)',
          set_price: '0',
        },
      ],
      card_images: [
        {
          id: 1,
          image_url: 'https://images.ygoprodeck.com/images/cards/14558127.jpg',
        },
      ],
      card_prices: [
        {
          cardmarket_price: '4.42',
          tcgplayer_price: '4.84',
          ebay_price: '15.99',
          amazon_price: '28.99',
          coolstufinic_price: '9.99',
        },
      ],
    },
    {
      name: 'Tearlaments Scheiren',
      type: 'Effect Monster',
      image: '/images/p2.jpg',
      level: 4,
      atk: 1800,
      def: 1300,
      race: 'Aqua',
      attribute: 'DARK',
      archetype: 'tearlaments',
      desc: `During your Main Phase: You can Special Summon this card from your hand, and if you do, send 1 monster from your hand to the GY, then, send the top 3 cards of your Deck to the GY. If this card is sent to the GY by card effect (except during the Damage Step): You can Fusion Summon 1 Fusion Monster from your Extra Deck, by placing Fusion Materials mentioned on it from your hand, field, and/or GY, including this card from your GY, on the bottom of the Deck in any order. You can only use each effect of "Tearlaments Scheiren" once per turn.`,
      card_sets: [
        {
          set_name: 'Power of the Elements',
          set_code: 'POTE-EN014',
          set_rarity: 'Super Rare',
          set_rarity_code: '(SR)',
          set_price: '0',
        },
      ],
      card_images: [
        {
          id: 572850,
          image_url: 'https://images.ygoprodeck.com/images/cards/572850.jpg',
        },
      ],
      card_prices: [
        {
          cardmarket_price: '1.79',
          tcgplayer_price: '1.43',
          ebay_price: '1.00',
          amazon_price: '1.49',
          coolstufinic_price: '1.99',
        },
      ],
    },
    {
      name: 'Despian Quaertis',
      type: 'Fusion monster',
      atk: 2500,
      def: 2500,
      race: 'Fiend',
      attribute: 'LIGHT',
      archetype: 'Despia',
      level: 8,
      desc: `1 "Despia" monster + 1 LIGHT or DARK monster
During the Main Phase (Quick Effect): You can change the ATK of all monsters currently on the field to 0 until the end of this turn, except Level 8 or higher Fusion Monsters. If this face-up card in its owner's control leaves the field because of an opponent's card effect: You can add to your hand, or Special Summon, 1 "Fallen of Albaz" or 1 "Despia" monster, from your Deck. You can only use each effect of "Despian Quaeritis" once per turn.`,
      card_sets: [
        {
          set_name: "2022 Tin of the Pharaoh's Gods",
          set_code: 'MP22-EN141',
          set_rarity: 'Prismatic Secret Rare',
          set_rarity_code: '(PScR)',
          set_price: '0',
        },
        {
          set_name: 'Dawn of Majesty',
          set_code: 'DAMA-EN034',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '15.31',
        },
      ],
      card_images: [
        {
          id: 72272462,
          image_url: 'https://images.ygoprodeck.com/images/cards/72272462.jpg',
        },
      ],
      card_prices: [
        {
          cardmarket_price: '0.71',
          tcgplayer_price: '0.59',
          ebay_price: '1.99',
          amazon_price: '0.25',
          coolstufinic_price: '1.99',
        },
      ],
    },
    {
      name: 'The Dark Magicians',
      type: 'Fusion Monster',
      price: 8.15,
      atk: 2800,
      def: 2300,
      level: 8,
      race: 'Spellcaster',
      attribute: 'DARK',
      archetype: 'Dark Magician',
      desc: `"Dark Magician" or "Dark Magician Girl" + 1 Spellcaster monster Once per turn, if a Spell/Trap Card or effect is activated (except during the Damage Step): You can draw 1 card, then if it was a Spell/Trap, you can Set it, and if it was a Trap or Quick-Play Spell, you can activate it this turn. If this card is destroyed: You can Special Summon both 1 "Dark Magician" and 1 "Dark Magician Girl" from your hand, Deck, and/or GY.`,
      card_sets: [
        {
          set_name: 'Battle of Chaos',
          set_code: 'BACH-EN100',
          set_rarity: 'Starlight Rare',
          set_rarity_code: '(StR)',
          set_price: '528.29',
        },
        {
          set_name: 'Legendary Duelists: Magical Hero',
          set_code: 'LED6-EN001',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '56.88',
        },
      ],
      card_images: [
        {
          id: 50237654,
          image_url: 'https://images.ygoprodeck.com/images/cards/50237654.jpg',
        },
      ],
      card_prices: [
        {
          cardmarket_price: '7.73',
          tcgplayer_price: '8.85',
          ebay_price: '12.99',
          amazon_price: '11.80',
          coolstufinic_price: '8.99',
        },
      ],
    },
    {
      name: 'Raigeki',
      type: 'Spell Card',
      frameType: 'spell',
      desc: 'Destroy all monsters your opponent controls.',
      race: 'Normal',
      card_sets: [
        {
          set_name: '2019 Gold Sarcophagus Tin',
          set_code: 'TN19-EN010',
          set_rarity: 'Prismatic Secret Rare',
          set_rarity_code: '(PScR)',
          set_price: '7.48',
        },
        {
          set_name: 'Battle Pack: Epic Dawn',
          set_code: 'BP01-EN032',
          set_rarity: 'Rare',
          set_rarity_code: '(R)',
          set_price: '6',
        },
        {
          set_name: 'Battle Pack: Epic Dawn',
          set_code: 'BP01-EN032',
          set_rarity: 'Starfoil Rare',
          set_rarity_code: '(SFR)',
          set_price: '7.05',
        },
        {
          set_name: 'Dark Beginning 1',
          set_code: 'DB1-EN114',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '40.48',
        },
        {
          set_name: 'Dark Legends',
          set_code: 'DLG1-EN006',
          set_rarity: 'Super Rare',
          set_rarity_code: '(SR)',
          set_price: '18.13',
        },
        {
          set_name: 'Legend of Blue Eyes White Dragon',
          set_code: 'LOB-053',
          set_rarity: 'Super Rare',
          set_rarity_code: '(SR)',
          set_price: '26.05',
        },
        {
          set_name: 'Legend of Blue Eyes White Dragon',
          set_code: 'LOB-E042',
          set_rarity: 'Super Rare',
          set_rarity_code: '(SR)',
          set_price: '23.45',
        },
        {
          set_name: 'Legend of Blue Eyes White Dragon',
          set_code: 'LOB-EN053',
          set_rarity: 'Super Rare',
          set_rarity_code: '(SR)',
          set_price: '14.08',
        },
        {
          set_name: "Legendary Collection 3: Yugi's World Mega Pack",
          set_code: 'LCYW-EN054',
          set_rarity: 'Secret Rare',
          set_rarity_code: '(ScR)',
          set_price: '14.79',
        },
        {
          set_name: "Legendary Collection 4: Joey's World Mega Pack",
          set_code: 'LCJW-EN057',
          set_rarity: 'Secret Rare',
          set_rarity_code: '(ScR)',
          set_price: '12.6',
        },
        {
          set_name: 'Legendary Collection Kaiba Mega Pack',
          set_code: 'LCKC-EN088',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '11.14',
        },
        {
          set_name: 'Maximum Gold: El Dorado',
          set_code: 'MGED-EN038',
          set_rarity: 'Premium Gold Rare',
          set_rarity_code: '(PG)',
          set_price: '0',
        },
        {
          set_name: 'Maximum Gold: El Dorado',
          set_code: 'MGED-EN038',
          set_rarity: 'Premium Gold Rare',
          set_rarity_code: '(PG)',
          set_price: '5.44',
        },
        {
          set_name: 'OTS Tournament Pack 2',
          set_code: 'OP02-EN003',
          set_rarity: 'Ultimate Rare',
          set_rarity_code: '(UtR)',
          set_price: '128.14',
        },
        {
          set_name: 'Premium Gold: Return of the Bling',
          set_code: 'PGL2-EN048',
          set_rarity: 'Gold Rare',
          set_rarity_code: '(GUR)',
          set_price: '6.06',
        },
        {
          set_name: 'Retro Pack',
          set_code: 'RP01-EN005',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '122.58',
        },
        {
          set_name: 'Structure Deck: Beware of Traptrix',
          set_code: 'SDBT-EN025',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '0',
        },
        {
          set_name: 'Structure Deck: Spirit Charmers',
          set_code: 'SDCH-EN021',
          set_rarity: 'Super Rare',
          set_rarity_code: '(SR)',
          set_price: '4.05',
        },
      ],
      banlist_info: { ban_ocg: 'Semi-Limited', ban_goat: 'Banned' },
      card_images: [
        {
          id: 12580477,
          image_url: 'https://images.ygoprodeck.com/images/cards/12580477.jpg',
          image_url_small:
            'https://images.ygoprodeck.com/images/cards_small/12580477.jpg',
          image_url_cropped:
            'https://images.ygoprodeck.com/images/cards_cropped/12580477.jpg',
        },
      ],
      card_prices: [
        {
          cardmarket_price: '4.42',
          tcgplayer_price: '1.99',
          ebay_price: '5.84',
          amazon_price: '3.90',
          coolstuffinc_price: '9.99',
        },
      ],
    },
    {
      name: 'Mirror Force',
      type: 'Trap Card',
      frameType: 'trap',
      desc: "When an opponent's monster declares an attack: Destroy all your opponent's Attack Position monsters.",
      race: 'Normal',
      card_sets: [
        {
          set_name: '2-Player Starter Deck: Yuya & Declan',
          set_code: 'YS15-END16',
          set_rarity: 'Super Rare',
          set_rarity_code: '(SR)',
          set_price: '5.66',
        },
        {
          set_name: 'Battle Pack: Epic Dawn',
          set_code: 'BP01-EN048',
          set_rarity: 'Rare',
          set_rarity_code: '(R)',
          set_price: '1.83',
        },
        {
          set_name: 'Battle Pack: Epic Dawn',
          set_code: 'BP01-EN048',
          set_rarity: 'Starfoil Rare',
          set_rarity_code: '(SFR)',
          set_price: '2.84',
        },
        {
          set_name: 'Dark Beginning 2',
          set_code: 'DB2-EN081',
          set_rarity: 'Super Rare',
          set_rarity_code: '(SR)',
          set_price: '18.78',
        },
        {
          set_name: 'Dark Legion Starter Deck',
          set_code: 'YS15-ENL22',
          set_rarity: 'Shatterfoil Rare',
          set_rarity_code: '(SHR)',
          set_price: '2.04',
        },
        {
          set_name: 'Dark Saviors',
          set_code: 'DASA-EN059',
          set_rarity: 'Super Rare',
          set_rarity_code: '(SR)',
          set_price: '1.92',
        },
        {
          set_name: 'Demo Deck 2016',
          set_code: 'DEM3-EN017',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '0.00',
        },
        {
          set_name: 'Dragunity Legion Structure Deck',
          set_code: 'SDDL-EN035',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '2.35',
        },
        {
          set_name: 'Duelist League 15 participation cards',
          set_code: 'DL15-EN018',
          set_rarity: 'Rare',
          set_rarity_code: '(R)',
          set_price: '13.9',
        },
        {
          set_name: 'Duelist Pack: Yugi',
          set_code: 'DPYG-EN027',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '12.09',
        },
        {
          set_name: 'Duelist Saga',
          set_code: 'DUSA-EN048',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '2.94',
        },
        {
          set_name: 'Egyptian God Deck: Slifer the Sky Dragon',
          set_code: 'EGS1-EN034',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.89',
        },
        {
          set_name: 'Gold Series',
          set_code: 'GLD1-EN039',
          set_rarity: 'Gold Rare',
          set_rarity_code: '(GUR)',
          set_price: '56.7',
        },
        {
          set_name: "Legendary Collection 3: Yugi's World Mega Pack",
          set_code: 'LCYW-EN091',
          set_rarity: 'Secret Rare',
          set_rarity_code: '(ScR)',
          set_price: '6.7',
        },
        {
          set_name: "Legendary Collection 4: Joey's World Mega Pack",
          set_code: 'LCJW-EN130',
          set_rarity: 'Secret Rare',
          set_rarity_code: '(ScR)',
          set_price: '5.21',
        },
        {
          set_name: 'Legendary Collection Kaiba Mega Pack',
          set_code: 'LCKC-EN053',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '2.56',
        },
        {
          set_name: 'Legendary Decks II',
          set_code: 'LDK2-ENY35',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.82',
        },
        {
          set_name: 'Legendary Dragon Decks',
          set_code: 'LEDD-ENA32',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.8',
        },
        {
          set_name: 'Magnificent Mavens',
          set_code: 'MAMA-EN115',
          set_rarity: "Ultra Rare (Pharaoh's Rare)",
          set_rarity_code: '',
          set_price: '0',
        },
        {
          set_name: 'Magnificent Mavens',
          set_code: 'MAMA-EN115',
          set_rarity: "Ultra Rare (Pharaoh's Rare)",
          set_rarity_code: '',
          set_price: '0',
        },
        {
          set_name: 'Metal Raiders',
          set_code: 'MRD-138',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '15.47',
        },
        {
          set_name: 'Metal Raiders',
          set_code: 'MRD-E138',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '19.79',
        },
        {
          set_name: 'Metal Raiders',
          set_code: 'MRD-EN138',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '32.13',
        },
        {
          set_name: 'Premium Gold',
          set_code: 'PGLD-EN059',
          set_rarity: 'Gold Rare',
          set_rarity_code: '(GUR)',
          set_price: '3.61',
        },
        {
          set_name: 'Saber Force Starter Deck',
          set_code: 'YS15-ENF21',
          set_rarity: 'Shatterfoil Rare',
          set_rarity_code: '(SHR)',
          set_price: '2.17',
        },
        {
          set_name: 'Space-Time Showdown Power-Up Pack',
          set_code: 'YS14-ENA12',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.7',
        },
        {
          set_name: 'Starter Deck: Codebreaker',
          set_code: 'YS18-EN036',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.7',
        },
        {
          set_name: 'Starter Deck: Dawn of the Xyz',
          set_code: 'YS11-EN036',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.75',
        },
        {
          set_name: 'Starter Deck: Link Strike',
          set_code: 'YS17-EN034',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.71',
        },
        {
          set_name: 'Starter Deck: Yugi Reloaded',
          set_code: 'YSYR-EN040',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.97',
        },
        {
          set_name: 'Structure Deck: Marik (TCG)',
          set_code: 'SDMA-EN030',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.87',
        },
        {
          set_name: 'Structure Deck: Rokket Revolt',
          set_code: 'SDRR-EN038',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.84',
        },
        {
          set_name: 'Structure Deck: Yugi Muto',
          set_code: 'SDMY-EN037',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.97',
        },
        {
          set_name: 'Super Starter Power-Up Pack',
          set_code: 'YS13-ENV14',
          set_rarity: 'Super Rare',
          set_rarity_code: '(SR)',
          set_price: '2.03',
        },
        {
          set_name: "Yugi's Legendary Decks",
          set_code: 'YGLD-ENA37',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.51',
        },
        {
          set_name: "Yugi's Legendary Decks",
          set_code: 'YGLD-ENB33',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '3.08',
        },
        {
          set_name: "Yugi's Legendary Decks",
          set_code: 'YGLD-ENC36',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.61',
        },
      ],
      banlist_info: { ban_goat: 'Limited' },
      card_images: [
        {
          id: 44095762,
          image_url: 'https://images.ygoprodeck.com/images/cards/44095762.jpg',
          image_url_small:
            'https://images.ygoprodeck.com/images/cards_small/44095762.jpg',
          image_url_cropped:
            'https://images.ygoprodeck.com/images/cards_cropped/44095762.jpg',
        },
      ],
      card_prices: [
        {
          cardmarket_price: '0.26',
          tcgplayer_price: '0.50',
          ebay_price: '2.29',
          amazon_price: '3.07',
          coolstuffinc_price: '4.99',
        },
      ],
    },
    {
      name: 'Elemental HERO The Shining',
      type: 'Fusion Monster',
      frameType: 'fusion',
      desc: '1 "Elemental HERO" monster + 1 LIGHT monster\nMust be Fusion Summoned and cannot be Special Summoned by other ways. This card gains 300 ATK for each of your banished "Elemental HERO" monsters. When this card is sent from the field to the Graveyard: You can target up to 2 of your banished "Elemental HERO" monsters; add those targets to your hand.',
      atk: 2600,
      def: 2100,
      level: 8,
      race: 'Warrior',
      attribute: 'LIGHT',
      archetype: 'Elemental HERO',
      card_sets: [
        {
          set_name: 'Premium Collection Tin',
          set_code: 'PRC1-ENV01',
          set_rarity: 'Secret Rare',
          set_rarity_code: '(ScR)',
          set_price: '7.06',
        },
        {
          set_name: 'Yu-Gi-Oh! GX Volume 6 promotional card',
          set_code: 'YG06-EN001',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '11.74',
        },
      ],
      card_images: [
        {
          id: 22061412,
          image_url: 'https://images.ygoprodeck.com/images/cards/22061412.jpg',
          image_url_small:
            'https://images.ygoprodeck.com/images/cards_small/22061412.jpg',
          image_url_cropped:
            'https://images.ygoprodeck.com/images/cards_cropped/22061412.jpg',
        },
      ],
      card_prices: [
        {
          cardmarket_price: '5.05',
          tcgplayer_price: '3.31',
          ebay_price: '3.49',
          amazon_price: '16.88',
          coolstuffinc_price: '4.99',
        },
      ],
    },
    {
      name: 'Fallen of Albaz',
      type: 'Effect Monster',
      frameType: 'effect',
      desc: 'If this card is Normal or Special Summoned (except during the Damage Step): You can discard 1 card; Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters on either field as Fusion Material, including this card, but you cannot use other monsters you control as Fusion Material. You can only use this effect of "Fallen of Albaz" once per turn.',
      atk: 1800,
      def: 0,
      level: 4,
      race: 'Dragon',
      attribute: 'DARK',
      archetype: 'Dogmatika',
      card_sets: [
        {
          set_name: '2021 Tin of Ancient Battles',
          set_code: 'MP21-EN107',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '3.2',
        },
        {
          set_name: 'OTS Tournament Pack 19',
          set_code: 'OP19-EN001',
          set_rarity: 'Ultimate Rare',
          set_rarity_code: '(UtR)',
          set_price: '38.2',
        },
        {
          set_name: 'OTS Tournament Pack 19 (POR)',
          set_code: 'OP19-PT001',
          set_rarity: 'Ultimate Rare',
          set_rarity_code: '(UtR)',
          set_price: '0',
        },
        {
          set_name: 'Rise of the Duelist',
          set_code: 'ROTD-EN011',
          set_rarity: 'Secret Rare',
          set_rarity_code: '(ScR)',
          set_price: '20.81',
        },
        {
          set_name: 'Structure Deck: Albaz Strike',
          set_code: 'SDAZ-EN004',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '1.23',
        },
      ],
      card_images: [
        {
          id: 68468459,
          image_url: 'https://images.ygoprodeck.com/images/cards/68468459.jpg',
          image_url_small:
            'https://images.ygoprodeck.com/images/cards_small/68468459.jpg',
          image_url_cropped:
            'https://images.ygoprodeck.com/images/cards_cropped/68468459.jpg',
        },
      ],
      card_prices: [
        {
          cardmarket_price: '0.23',
          tcgplayer_price: '0.31',
          ebay_price: '2.95',
          amazon_price: '0.43',
          coolstuffinc_price: '1.49',
        },
      ],
    },
    {
      name: 'Stardust Dragon',
      type: 'Synchro Monster',
      frameType: 'synchro',
      desc: '1 Tuner + 1+ non-Tuner monsters\r\nWhen a card or effect is activated that would destroy a card(s) on the field (Quick Effect): You can Tribute this card; negate the activation, and if you do, destroy it. During the End Phase, if this effect was activated this turn (and was not negated): You can Special Summon this card from your GY.',
      atk: 2500,
      def: 2000,
      level: 8,
      race: 'Dragon',
      attribute: 'WIND',
      archetype: 'Stardust',
      card_sets: [
        {
          set_name: 'Collectible Tins 2008 Wave 1',
          set_code: 'CT05-EN001',
          set_rarity: 'Secret Rare',
          set_rarity_code: '(ScR)',
          set_price: '22.97',
        },
        {
          set_name: 'Collectible Tins 2010 Wave 2',
          set_code: 'CT07-EN021',
          set_rarity: 'Super Rare',
          set_rarity_code: '(SR)',
          set_price: '5.69',
        },
        {
          set_name: 'Dawn of Majesty',
          set_code: 'DAMA-EN100',
          set_rarity: 'Starlight Rare',
          set_rarity_code: '(StR)',
          set_price: '635.43',
        },
        {
          set_name: 'Duel Power',
          set_code: 'DUPO-EN103',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '3.1',
        },
        {
          set_name: 'Duelist Pack: Yusei',
          set_code: 'DP08-EN014',
          set_rarity: 'Super Rare',
          set_rarity_code: '(SR)',
          set_price: '4.38',
        },
        {
          set_name: 'Gold Series 3',
          set_code: 'GLD3-EN037',
          set_rarity: 'Gold Rare',
          set_rarity_code: '(GUR)',
          set_price: '13.49',
        },
        {
          set_name: "Legendary Collection 5D's Mega Pack",
          set_code: 'LC5D-EN031',
          set_rarity: 'Common',
          set_rarity_code: '(C)',
          set_price: '4.09',
        },
        {
          set_name: "Legendary Collection 5D's Mega Pack",
          set_code: 'LC5D-EN031',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '14.78',
        },
        {
          set_name: 'Premium Gold',
          set_code: 'PGLD-EN076',
          set_rarity: 'Gold Rare',
          set_rarity_code: '(GUR)',
          set_price: '11.18',
        },
        {
          set_name: 'Shadow Specters: Special Edition',
          set_code: 'SHSP-ENSE1',
          set_rarity: 'Super Rare',
          set_rarity_code: '(SR)',
          set_price: '5.28',
        },
        {
          set_name: 'The Duelist Genesis',
          set_code: 'TDGS-EN040',
          set_rarity: 'Ghost Rare',
          set_rarity_code: '(GR)',
          set_price: '431.02',
        },
        {
          set_name: 'The Duelist Genesis',
          set_code: 'TDGS-EN040',
          set_rarity: 'Ultimate Rare',
          set_rarity_code: '(UtR)',
          set_price: '74.46',
        },
        {
          set_name: 'The Duelist Genesis',
          set_code: 'TDGS-EN040',
          set_rarity: 'Ultra Rare',
          set_rarity_code: '(UR)',
          set_price: '31.54',
        },
        {
          set_name: 'Toon Chaos',
          set_code: 'TOCH-EN050',
          set_rarity: "Collector's Rare",
          set_rarity_code: '(CR)',
          set_price: '2.9',
        },
        {
          set_name: 'Toon Chaos',
          set_code: 'TOCH-EN050',
          set_rarity: 'Rare',
          set_rarity_code: '(R)',
          set_price: '3.37',
        },
        {
          set_name: 'Turbo Pack: Booster Six',
          set_code: 'TU06-EN007',
          set_rarity: 'Rare',
          set_rarity_code: '(R)',
          set_price: '4.76',
        },
      ],
      card_images: [
        {
          id: 44508095,
          image_url: 'https://images.ygoprodeck.com/images/cards/44508095.jpg',
          image_url_small:
            'https://images.ygoprodeck.com/images/cards_small/44508095.jpg',
          image_url_cropped:
            'https://images.ygoprodeck.com/images/cards_cropped/44508095.jpg',
        },
        {
          id: 44508094,
          image_url: 'https://images.ygoprodeck.com/images/cards/44508094.jpg',
          image_url_small:
            'https://images.ygoprodeck.com/images/cards_small/44508094.jpg',
          image_url_cropped:
            'https://images.ygoprodeck.com/images/cards_cropped/44508094.jpg',
        },
      ],
      card_prices: [
        {
          cardmarket_price: '0.44',
          tcgplayer_price: '0.78',
          ebay_price: '4.95',
          amazon_price: '2.49',
          coolstuffinc_price: '599.99',
        },
      ],
    },
    {
      name: 'Invasion of Chaos',
      desc: 'Invasion of Chaos unleashed a variety of powerful cards that rewarded Duelists who packed their Decks with LIGHT and DARK Attribute monsters. The legendary Black Luster Soldier – Envoy of the Beginning and Chaos Emperor Dragon – Envoy of the End dominated Duels and the Spell-retrieving Dark Magician of Chaos joined them thanks to the incredibly powerful Dimension Fusion Spell Card! This printing will feature both Secret Rares from the set.',
      category: 'set',
      brand: 'Yugioh',
      card_sets: [
        {
          set_name: 'Invasion of Choas',
          set_code: 'TDGS-EN040',
          set_rarity: 'Ultimate Rare',
          set_rarity_code: '(UtR)',
          set_price: '4.99',
        },
      ],
      card_images: [
        {
          id: 44508092,
          image_url:
            'https://img.yugioh-card.com/en/wp-content/uploads/2022/12/IOC_25th_550.png',
        },
      ],
      card_prices: [
        {
          cardmarket_price: '4.99',
          tcgplayer_price: '4.99',
        },
      ],
    },
  ],
};

export default data;
